# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinss', '0002_join_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
