# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinss', '0005_auto_20160322_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='join',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='joinss.Join'),
        ),
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='ABC', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='joinfriends',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinss.Join'),
        ),
    ]
